version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  name: react-app-build
  discard-paths: no
  base-directory: dist  
  acl: bucket-owner-full-control
